// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.aimstair.reminder_app.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object PlatformApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * A calendar on the device (S-04 picker).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceCalendar (
  val id: String,
  val name: String,
  /** ARGB. */
  val color: Long,
  val accountName: String,
  /** The contacts/"Birthdays" calendar (CAL-4 rule 1, CON-7). */
  val isBirthdays: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceCalendar {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val color = pigeonVar_list[2] as Long
      val accountName = pigeonVar_list[3] as String
      val isBirthdays = pigeonVar_list[4] as Boolean
      return DeviceCalendar(id, name, color, accountName, isBirthdays)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      color,
      accountName,
      isBirthdays,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceCalendar
    return PlatformApiPigeonUtils.deepEquals(this.id, other.id) && PlatformApiPigeonUtils.deepEquals(this.name, other.name) && PlatformApiPigeonUtils.deepEquals(this.color, other.color) && PlatformApiPigeonUtils.deepEquals(this.accountName, other.accountName) && PlatformApiPigeonUtils.deepEquals(this.isBirthdays, other.isBirthdays)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.id)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.name)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.color)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.accountName)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.isBirthdays)
    return result
  }
  override fun toString(): String {
    return "DeviceCalendar(id=$id, name=$name, color=$color, accountName=$accountName, isBirthdays=$isBirthdays)"
  }
}

/**
 * One event instance from CalendarContract.Instances.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceEvent (
  val calendarId: String,
  val eventId: String,
  val title: String,
  val beginMs: Long,
  val endMs: Long,
  val allDay: Boolean,
  val timeZone: String? = null,
  val rrule: String? = null,
  /** Attendees other than the calendar's owner (CAL-4 rule 3). */
  val otherAttendees: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeviceEvent {
      val calendarId = pigeonVar_list[0] as String
      val eventId = pigeonVar_list[1] as String
      val title = pigeonVar_list[2] as String
      val beginMs = pigeonVar_list[3] as Long
      val endMs = pigeonVar_list[4] as Long
      val allDay = pigeonVar_list[5] as Boolean
      val timeZone = pigeonVar_list[6] as String?
      val rrule = pigeonVar_list[7] as String?
      val otherAttendees = pigeonVar_list[8] as Long
      return DeviceEvent(calendarId, eventId, title, beginMs, endMs, allDay, timeZone, rrule, otherAttendees)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      calendarId,
      eventId,
      title,
      beginMs,
      endMs,
      allDay,
      timeZone,
      rrule,
      otherAttendees,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DeviceEvent
    return PlatformApiPigeonUtils.deepEquals(this.calendarId, other.calendarId) && PlatformApiPigeonUtils.deepEquals(this.eventId, other.eventId) && PlatformApiPigeonUtils.deepEquals(this.title, other.title) && PlatformApiPigeonUtils.deepEquals(this.beginMs, other.beginMs) && PlatformApiPigeonUtils.deepEquals(this.endMs, other.endMs) && PlatformApiPigeonUtils.deepEquals(this.allDay, other.allDay) && PlatformApiPigeonUtils.deepEquals(this.timeZone, other.timeZone) && PlatformApiPigeonUtils.deepEquals(this.rrule, other.rrule) && PlatformApiPigeonUtils.deepEquals(this.otherAttendees, other.otherAttendees)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.calendarId)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.eventId)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.title)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.beginMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.endMs)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.allDay)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.timeZone)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.rrule)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.otherAttendees)
    return result
  }
  override fun toString(): String {
    return "DeviceEvent(calendarId=$calendarId, eventId=$eventId, title=$title, beginMs=$beginMs, endMs=$endMs, allDay=$allDay, timeZone=$timeZone, rrule=$rrule, otherAttendees=$otherAttendees)"
  }
}
private open class PlatformApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceCalendar.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DeviceCalendar -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DeviceEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlatformHostApi {
  fun hasCalendarPermission(): Boolean
  suspend fun requestCalendarPermission(): Boolean
  fun readCalendars(): List<DeviceCalendar>
  fun readEvents(fromMs: Long, toMs: Long, calendarIds: List<String>): List<DeviceEvent>
  /** S-63: pending shared text, returned once. */
  fun takeSharedText(): String?
  /** Pending launch action, returned once: `capture` or `open:<alarmKey>`. */
  fun takeLaunchAction(): String?
  /** DAT-5: save a backup through the system file picker; null if cancelled. */
  suspend fun saveBackup(fileName: String, json: String): String?
  /** DAT-5: pick a backup file and return its text; null if cancelled. */
  suspend fun openBackup(): String?
  /** S-61: JSON `{"items":[{"title","when"}],"empty":"…"}` for the home-screen widget. */
  fun updateWidget(json: String)
  /** PRM-4: Build.MANUFACTURER for the battery tip. */
  fun deviceBrand(): String
  /** S-58 feedback email footer: "samsung SM-A736B · Android 15 (API 35)". Device info only. */
  fun deviceInfo(): String
  /** Opens the system share sheet with [text] (All clear "share", mockup 10). Only what the user sees. */
  fun shareText(text: String)

  companion object {
    /** The codec used by PlatformHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `PlatformHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlatformHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.hasCalendarPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.hasCalendarPermission())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.requestCalendarPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestCalendarPermission())
              } catch (exception: Throwable) {
                PlatformApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.readCalendars$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.readCalendars())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.readEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fromMsArg = args[0] as Long
            val toMsArg = args[1] as Long
            val calendarIdsArg = args[2] as List<String>
            val wrapped: List<Any?> = try {
              listOf(api.readEvents(fromMsArg, toMsArg, calendarIdsArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.takeSharedText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takeSharedText())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.takeLaunchAction$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takeLaunchAction())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.saveBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fileNameArg = args[0] as String
            val jsonArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.saveBackup(fileNameArg, jsonArg))
              } catch (exception: Throwable) {
                PlatformApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.openBackup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.openBackup())
              } catch (exception: Throwable) {
                PlatformApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.updateWidget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jsonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.updateWidget(jsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.deviceBrand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.deviceBrand())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.deviceInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.deviceInfo())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.PlatformHostApi.shareText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.shareText(textArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PlatformFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PlatformFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
  }
  suspend fun onSharedText(textArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.reminder_app.PlatformFlutterApi.onSharedText$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(textArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(PlatformApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun onLaunchAction(actionArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.reminder_app.PlatformFlutterApi.onLaunchAction$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(actionArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(PlatformApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
