// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package app.aimstair.reminder_app.alarms

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AlarmApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * One alarm the native side should fire. Key = `occurrence_id:stage:nag_seq` (SCH-4).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AlarmSpec (
  val key: String,
  val fireAtUtcMs: Long,
  val title: String,
  val body: String,
  /** Which notification buttons to show (NTF-2): task | occasion_prep | occasion_day | meeting | test */
  val kind: String,
  /** SCH-7: alarms later than this are recorded as missed instead of shown. */
  val lateCutoffMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AlarmSpec {
      val key = pigeonVar_list[0] as String
      val fireAtUtcMs = pigeonVar_list[1] as Long
      val title = pigeonVar_list[2] as String
      val body = pigeonVar_list[3] as String
      val kind = pigeonVar_list[4] as String
      val lateCutoffMs = pigeonVar_list[5] as Long
      return AlarmSpec(key, fireAtUtcMs, title, body, kind, lateCutoffMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      key,
      fireAtUtcMs,
      title,
      body,
      kind,
      lateCutoffMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AlarmSpec
    return AlarmApiPigeonUtils.deepEquals(this.key, other.key) && AlarmApiPigeonUtils.deepEquals(this.fireAtUtcMs, other.fireAtUtcMs) && AlarmApiPigeonUtils.deepEquals(this.title, other.title) && AlarmApiPigeonUtils.deepEquals(this.body, other.body) && AlarmApiPigeonUtils.deepEquals(this.kind, other.kind) && AlarmApiPigeonUtils.deepEquals(this.lateCutoffMs, other.lateCutoffMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.key)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.fireAtUtcMs)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.title)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.body)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.kind)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.lateCutoffMs)
    return result
  }
  override fun toString(): String {
    return "AlarmSpec(key=$key, fireAtUtcMs=$fireAtUtcMs, title=$title, body=$body, kind=$kind, lateCutoffMs=$lateCutoffMs)"
  }
}

/**
 * An alarm currently registered natively — the same fields as [AlarmSpec] plus whether it's exact.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegisteredAlarm (
  val spec: AlarmSpec,
  /** False when exact alarms aren't allowed and an inexact window was used (SCH-9). */
  val exact: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisteredAlarm {
      val spec = pigeonVar_list[0] as AlarmSpec
      val exact = pigeonVar_list[1] as Boolean
      return RegisteredAlarm(spec, exact)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      spec,
      exact,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegisteredAlarm
    return AlarmApiPigeonUtils.deepEquals(this.spec, other.spec) && AlarmApiPigeonUtils.deepEquals(this.exact, other.exact)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.spec)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.exact)
    return result
  }
  override fun toString(): String {
    return "RegisteredAlarm(spec=$spec, exact=$exact)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PermissionState (
  val notifications: Boolean,
  val exactAlarms: Boolean,
  val ignoringBatteryOptimizations: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionState {
      val notifications = pigeonVar_list[0] as Boolean
      val exactAlarms = pigeonVar_list[1] as Boolean
      val ignoringBatteryOptimizations = pigeonVar_list[2] as Boolean
      return PermissionState(notifications, exactAlarms, ignoringBatteryOptimizations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      notifications,
      exactAlarms,
      ignoringBatteryOptimizations,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PermissionState
    return AlarmApiPigeonUtils.deepEquals(this.notifications, other.notifications) && AlarmApiPigeonUtils.deepEquals(this.exactAlarms, other.exactAlarms) && AlarmApiPigeonUtils.deepEquals(this.ignoringBatteryOptimizations, other.ignoringBatteryOptimizations)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.notifications)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.exactAlarms)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.ignoringBatteryOptimizations)
    return result
  }
  override fun toString(): String {
    return "PermissionState(notifications=$notifications, exactAlarms=$exactAlarms, ignoringBatteryOptimizations=$ignoringBatteryOptimizations)"
  }
}

/**
 * A notification button tapped while Flutter may not have been running.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class JournalEntry (
  val id: Long,
  val alarmKey: String,
  /** done | snooze | tomorrow | prepared | undo */
  val action: String,
  val actedAtMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JournalEntry {
      val id = pigeonVar_list[0] as Long
      val alarmKey = pigeonVar_list[1] as String
      val action = pigeonVar_list[2] as String
      val actedAtMs = pigeonVar_list[3] as Long
      return JournalEntry(id, alarmKey, action, actedAtMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      alarmKey,
      action,
      actedAtMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as JournalEntry
    return AlarmApiPigeonUtils.deepEquals(this.id, other.id) && AlarmApiPigeonUtils.deepEquals(this.alarmKey, other.alarmKey) && AlarmApiPigeonUtils.deepEquals(this.action, other.action) && AlarmApiPigeonUtils.deepEquals(this.actedAtMs, other.actedAtMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.id)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.alarmKey)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.action)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.actedAtMs)
    return result
  }
  override fun toString(): String {
    return "JournalEntry(id=$id, alarmKey=$alarmKey, action=$action, actedAtMs=$actedAtMs)"
  }
}

/**
 * Delivery record for metrics (D4) and the test reminder (PRM-7).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FireLogEntry (
  val alarmKey: String,
  val scheduledAtMs: Long,
  val firedAtMs: Long,
  /** shown | late | missed */
  val outcome: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FireLogEntry {
      val alarmKey = pigeonVar_list[0] as String
      val scheduledAtMs = pigeonVar_list[1] as Long
      val firedAtMs = pigeonVar_list[2] as Long
      val outcome = pigeonVar_list[3] as String
      return FireLogEntry(alarmKey, scheduledAtMs, firedAtMs, outcome)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alarmKey,
      scheduledAtMs,
      firedAtMs,
      outcome,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FireLogEntry
    return AlarmApiPigeonUtils.deepEquals(this.alarmKey, other.alarmKey) && AlarmApiPigeonUtils.deepEquals(this.scheduledAtMs, other.scheduledAtMs) && AlarmApiPigeonUtils.deepEquals(this.firedAtMs, other.firedAtMs) && AlarmApiPigeonUtils.deepEquals(this.outcome, other.outcome)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.alarmKey)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.scheduledAtMs)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.firedAtMs)
    result = 31 * result + AlarmApiPigeonUtils.deepHash(this.outcome)
    return result
  }
  override fun toString(): String {
    return "FireLogEntry(alarmKey=$alarmKey, scheduledAtMs=$scheduledAtMs, firedAtMs=$firedAtMs, outcome=$outcome)"
  }
}
private open class AlarmApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AlarmSpec.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisteredAlarm.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionState.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JournalEntry.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FireLogEntry.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AlarmSpec -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RegisteredAlarm -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PermissionState -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is JournalEntry -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is FireLogEntry -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AlarmHostApi {
  /** Replace the registered set with [alarms] (diff by key: add, update, cancel) — SCH-4. */
  fun sync(alarms: List<AlarmSpec>)
  /** Cancel alarms and remove their notifications — OCC-4, DAT-2. */
  fun cancel(keys: List<String>)
  fun registered(): List<RegisteredAlarm>
  fun getPermissionState(): PermissionState
  fun requestNotificationPermission()
  fun openExactAlarmSettings()
  fun openBatteryOptimizationSettings()
  fun readJournal(): List<JournalEntry>
  fun markApplied(ids: List<Long>)
  fun getFireLog(sinceMs: Long): List<FireLogEntry>
  fun clearLogs()

  companion object {
    /** The codec used by AlarmHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      AlarmApiPigeonCodec()
    }
    /** Sets up an instance of `AlarmHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AlarmHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.sync$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alarmsArg = args[0] as List<AlarmSpec>
            val wrapped: List<Any?> = try {
              api.sync(alarmsArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keysArg = args[0] as List<String>
            val wrapped: List<Any?> = try {
              api.cancel(keysArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.registered$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.registered())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.getPermissionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPermissionState())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.requestNotificationPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.requestNotificationPermission()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.openExactAlarmSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openExactAlarmSettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.openBatteryOptimizationSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openBatteryOptimizationSettings()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.readJournal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.readJournal())
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.markApplied$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idsArg = args[0] as List<Long>
            val wrapped: List<Any?> = try {
              api.markApplied(idsArg)
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.getFireLog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sinceMsArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.getFireLog(sinceMsArg))
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.reminder_app.AlarmHostApi.clearLogs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearLogs()
              listOf(null)
            } catch (exception: Throwable) {
              AlarmApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
