// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// One alarm the native side should fire. Key = `occurrence_id:stage:nag_seq` (SCH-4).
class AlarmSpec {
  AlarmSpec({
    required this.key,
    required this.fireAtUtcMs,
    required this.title,
    required this.body,
    required this.kind,
    required this.lateCutoffMs,
  });

  String key;

  int fireAtUtcMs;

  String title;

  String body;

  /// Which notification buttons to show (NTF-2): task | occasion_prep | occasion_day | meeting | test
  String kind;

  /// SCH-7: alarms later than this are recorded as missed instead of shown.
  int lateCutoffMs;

  List<Object?> _toList() {
    return <Object?>[
      key,
      fireAtUtcMs,
      title,
      body,
      kind,
      lateCutoffMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AlarmSpec decode(Object result) {
    result as List<Object?>;
    return AlarmSpec(
      key: result[0]! as String,
      fireAtUtcMs: result[1]! as int,
      title: result[2]! as String,
      body: result[3]! as String,
      kind: result[4]! as String,
      lateCutoffMs: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AlarmSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(key, other.key) && _deepEquals(fireAtUtcMs, other.fireAtUtcMs) && _deepEquals(title, other.title) && _deepEquals(body, other.body) && _deepEquals(kind, other.kind) && _deepEquals(lateCutoffMs, other.lateCutoffMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AlarmSpec(key: $key, fireAtUtcMs: $fireAtUtcMs, title: $title, body: $body, kind: $kind, lateCutoffMs: $lateCutoffMs)';
  }
}

/// An alarm currently registered natively — the same fields as [AlarmSpec] plus whether it's exact.
class RegisteredAlarm {
  RegisteredAlarm({
    required this.spec,
    required this.exact,
  });

  AlarmSpec spec;

  /// False when exact alarms aren't allowed and an inexact window was used (SCH-9).
  bool exact;

  List<Object?> _toList() {
    return <Object?>[
      spec,
      exact,
    ];
  }

  Object encode() {
    return _toList();  }

  static RegisteredAlarm decode(Object result) {
    result as List<Object?>;
    return RegisteredAlarm(
      spec: result[0]! as AlarmSpec,
      exact: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegisteredAlarm || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(spec, other.spec) && _deepEquals(exact, other.exact);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RegisteredAlarm(spec: $spec, exact: $exact)';
  }
}

class PermissionState {
  PermissionState({
    required this.notifications,
    required this.exactAlarms,
    required this.ignoringBatteryOptimizations,
  });

  bool notifications;

  bool exactAlarms;

  bool ignoringBatteryOptimizations;

  List<Object?> _toList() {
    return <Object?>[
      notifications,
      exactAlarms,
      ignoringBatteryOptimizations,
    ];
  }

  Object encode() {
    return _toList();  }

  static PermissionState decode(Object result) {
    result as List<Object?>;
    return PermissionState(
      notifications: result[0]! as bool,
      exactAlarms: result[1]! as bool,
      ignoringBatteryOptimizations: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PermissionState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(notifications, other.notifications) && _deepEquals(exactAlarms, other.exactAlarms) && _deepEquals(ignoringBatteryOptimizations, other.ignoringBatteryOptimizations);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PermissionState(notifications: $notifications, exactAlarms: $exactAlarms, ignoringBatteryOptimizations: $ignoringBatteryOptimizations)';
  }
}

/// A notification button tapped while Flutter may not have been running.
class JournalEntry {
  JournalEntry({
    required this.id,
    required this.alarmKey,
    required this.action,
    required this.actedAtMs,
  });

  int id;

  String alarmKey;

  /// done | snooze | tomorrow | prepared | undo
  String action;

  int actedAtMs;

  List<Object?> _toList() {
    return <Object?>[
      id,
      alarmKey,
      action,
      actedAtMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static JournalEntry decode(Object result) {
    result as List<Object?>;
    return JournalEntry(
      id: result[0]! as int,
      alarmKey: result[1]! as String,
      action: result[2]! as String,
      actedAtMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! JournalEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(alarmKey, other.alarmKey) && _deepEquals(action, other.action) && _deepEquals(actedAtMs, other.actedAtMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'JournalEntry(id: $id, alarmKey: $alarmKey, action: $action, actedAtMs: $actedAtMs)';
  }
}

/// Delivery record for metrics (D4) and the test reminder (PRM-7).
class FireLogEntry {
  FireLogEntry({
    required this.alarmKey,
    required this.scheduledAtMs,
    required this.firedAtMs,
    required this.outcome,
  });

  String alarmKey;

  int scheduledAtMs;

  int firedAtMs;

  /// shown | late | missed
  String outcome;

  List<Object?> _toList() {
    return <Object?>[
      alarmKey,
      scheduledAtMs,
      firedAtMs,
      outcome,
    ];
  }

  Object encode() {
    return _toList();  }

  static FireLogEntry decode(Object result) {
    result as List<Object?>;
    return FireLogEntry(
      alarmKey: result[0]! as String,
      scheduledAtMs: result[1]! as int,
      firedAtMs: result[2]! as int,
      outcome: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FireLogEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alarmKey, other.alarmKey) && _deepEquals(scheduledAtMs, other.scheduledAtMs) && _deepEquals(firedAtMs, other.firedAtMs) && _deepEquals(outcome, other.outcome);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FireLogEntry(alarmKey: $alarmKey, scheduledAtMs: $scheduledAtMs, firedAtMs: $firedAtMs, outcome: $outcome)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AlarmSpec) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is RegisteredAlarm) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PermissionState) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is JournalEntry) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is FireLogEntry) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return AlarmSpec.decode(readValue(buffer)!);
      case 130:
        return RegisteredAlarm.decode(readValue(buffer)!);
      case 131:
        return PermissionState.decode(readValue(buffer)!);
      case 132:
        return JournalEntry.decode(readValue(buffer)!);
      case 133:
        return FireLogEntry.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AlarmHostApi {
  /// Constructor for [AlarmHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AlarmHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  /// Replace the registered set with [alarms] (diff by key: add, update, cancel) — SCH-4.
  Future<void> sync(List<AlarmSpec> alarms) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.sync$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alarms]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Cancel alarms and remove their notifications — OCC-4, DAT-2.
  Future<void> cancel(List<String> keys) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[keys]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<RegisteredAlarm>> registered() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.registered$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<RegisteredAlarm>();
  }

  Future<PermissionState> getPermissionState() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.getPermissionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PermissionState;
  }

  Future<void> requestNotificationPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.requestNotificationPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openExactAlarmSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.openExactAlarmSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openBatteryOptimizationSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.openBatteryOptimizationSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<JournalEntry>> readJournal() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.readJournal$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<JournalEntry>();
  }

  Future<void> markApplied(List<int> ids) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.markApplied$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[ids]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<FireLogEntry>> getFireLog(int sinceMs) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.getFireLog$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sinceMs]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<FireLogEntry>();
  }

  Future<void> clearLogs() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.AlarmHostApi.clearLogs$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
