// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// A calendar on the device (S-04 picker).
class DeviceCalendar {
  DeviceCalendar({
    required this.id,
    required this.name,
    required this.color,
    required this.accountName,
    required this.isBirthdays,
  });

  String id;

  String name;

  /// ARGB.
  int color;

  String accountName;

  /// The contacts/"Birthdays" calendar (CAL-4 rule 1, CON-7).
  bool isBirthdays;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      color,
      accountName,
      isBirthdays,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceCalendar decode(Object result) {
    result as List<Object?>;
    return DeviceCalendar(
      id: result[0]! as String,
      name: result[1]! as String,
      color: result[2]! as int,
      accountName: result[3]! as String,
      isBirthdays: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceCalendar || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(color, other.color) && _deepEquals(accountName, other.accountName) && _deepEquals(isBirthdays, other.isBirthdays);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceCalendar(id: $id, name: $name, color: $color, accountName: $accountName, isBirthdays: $isBirthdays)';
  }
}

/// One event instance from CalendarContract.Instances.
class DeviceEvent {
  DeviceEvent({
    required this.calendarId,
    required this.eventId,
    required this.title,
    required this.beginMs,
    required this.endMs,
    required this.allDay,
    this.timeZone,
    this.rrule,
    required this.otherAttendees,
  });

  String calendarId;

  String eventId;

  String title;

  int beginMs;

  int endMs;

  bool allDay;

  String? timeZone;

  String? rrule;

  /// Attendees other than the calendar's owner (CAL-4 rule 3).
  int otherAttendees;

  List<Object?> _toList() {
    return <Object?>[
      calendarId,
      eventId,
      title,
      beginMs,
      endMs,
      allDay,
      timeZone,
      rrule,
      otherAttendees,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceEvent decode(Object result) {
    result as List<Object?>;
    return DeviceEvent(
      calendarId: result[0]! as String,
      eventId: result[1]! as String,
      title: result[2]! as String,
      beginMs: result[3]! as int,
      endMs: result[4]! as int,
      allDay: result[5]! as bool,
      timeZone: result[6] as String?,
      rrule: result[7] as String?,
      otherAttendees: result[8]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(calendarId, other.calendarId) && _deepEquals(eventId, other.eventId) && _deepEquals(title, other.title) && _deepEquals(beginMs, other.beginMs) && _deepEquals(endMs, other.endMs) && _deepEquals(allDay, other.allDay) && _deepEquals(timeZone, other.timeZone) && _deepEquals(rrule, other.rrule) && _deepEquals(otherAttendees, other.otherAttendees);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DeviceEvent(calendarId: $calendarId, eventId: $eventId, title: $title, beginMs: $beginMs, endMs: $endMs, allDay: $allDay, timeZone: $timeZone, rrule: $rrule, otherAttendees: $otherAttendees)';
  }
}

/// ATT-3: a file the user picked, copied into app storage.
class PickedFile {
  PickedFile({
    required this.path,
    required this.name,
    required this.size,
    this.mime,
  });

  String path;

  String name;

  int size;

  String? mime;

  List<Object?> _toList() {
    return <Object?>[
      path,
      name,
      size,
      mime,
    ];
  }

  Object encode() {
    return _toList();  }

  static PickedFile decode(Object result) {
    result as List<Object?>;
    return PickedFile(
      path: result[0]! as String,
      name: result[1]! as String,
      size: result[2]! as int,
      mime: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PickedFile || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) && _deepEquals(name, other.name) && _deepEquals(size, other.size) && _deepEquals(mime, other.mime);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PickedFile(path: $path, name: $name, size: $size, mime: $mime)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is DeviceCalendar) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceEvent) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is PickedFile) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return DeviceCalendar.decode(readValue(buffer)!);
      case 130:
        return DeviceEvent.decode(readValue(buffer)!);
      case 131:
        return PickedFile.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PlatformHostApi {
  /// Constructor for [PlatformHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PlatformHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<bool> hasCalendarPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.hasCalendarPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> requestCalendarPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.requestCalendarPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<List<DeviceCalendar>> readCalendars() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.readCalendars$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<DeviceCalendar>();
  }

  Future<List<DeviceEvent>> readEvents(int fromMs, int toMs, List<String> calendarIds) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.readEvents$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fromMs, toMs, calendarIds]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<DeviceEvent>();
  }

  /// S-63: pending shared text, returned once.
  Future<String?> takeSharedText() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.takeSharedText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// Pending launch action, returned once: `capture` or `open:<alarmKey>`.
  Future<String?> takeLaunchAction() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.takeLaunchAction$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// DAT-5: save a backup through the system file picker; null if cancelled.
  Future<String?> saveBackup(String fileName, String json) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.saveBackup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[fileName, json]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// DAT-5: pick a backup file and return its text; null if cancelled.
  Future<String?> openBackup() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.openBackup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// S-61: JSON `{"items":[{"title","when"}],"empty":"…"}` for the home-screen widget.
  Future<void> updateWidget(String json) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.updateWidget$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[json]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// PRM-4: Build.MANUFACTURER for the battery tip.
  Future<String> deviceBrand() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.deviceBrand$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// S-58 feedback email footer: "samsung SM-A736B · Android 15 (API 35)". Device info only.
  Future<String> deviceInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.deviceInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// ATT-3: pick any file and copy it into app storage; null if cancelled.
  Future<PickedFile?> pickAttachment() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.pickAttachment$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as PickedFile?;
  }

  /// ATT-4: open a stored file in another app; false when no app can open it or it's gone.
  Future<bool> openAttachment(String path, String? mime) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.openAttachment$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, mime]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// ATT-6: remove a stored file (attachment removed in the editor).
  Future<void> deleteAttachment(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.deleteAttachment$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Opens the system share sheet with [text] (All clear "share", mockup 10). Only what the user sees.
  Future<void> shareText(String text) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.reminder_app.PlatformHostApi.shareText$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[text]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class PlatformFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onSharedText(String text);

  void onLaunchAction(String action);

  static void setUp(PlatformFlutterApi? api, {
    BinaryMessenger? binaryMessenger, 
    String messageChannelSuffix = '',
  }) 
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.reminder_app.PlatformFlutterApi.onSharedText$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_text = args[0]! as String;
          try {
            api.onSharedText(arg_text);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.reminder_app.PlatformFlutterApi.onLaunchAction$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_action = args[0]! as String;
          try {
            api.onLaunchAction(arg_action);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
